import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import React, {useEffect, useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [movies, setMovies] = useState([]);
    useEffect(() => {
        async function fetchData() {
            const res = await fetch(`https://api.themoviedb.org/3/movie/popular?api_key=b5cbbe7b6a6f3af9ca2350d1dd51eb01`);
            const json = await res.json();
            setMovies(json.results);
        }
        fetchData();
    }, []);
  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["navbar"] + " " + styles["container"]}>
        <Image src="./image.svg" alt="" width={75} height={75}/>
        <div className={styles.menu}>
          <Link href="/">Accueil</Link>
          <Link href="/series">Séries</Link>
          <Link href="/animes">Animes</Link>
          <Link href="/top">Top de la semaine</Link>
        </div>
          <div className={styles.blocklogsignin}>
              <Link href="/register">Sign In</Link>
              <Link href="/login">Log In</Link>
          </div>
      </div>
      <main className={styles.main}>
          <div className={styles.trend}>
          <h1 className={styles["p1"] + " " + styles["title"]}>Films du moment</h1>
       <div className={styles.flex}>
           <div>
               <ul>
                   {movies.slice(0, 10).map((movie,index) => (
                       <li key={index}>
                           <img className={styles.postmovie} src={`https://image.tmdb.org/t/p/w500${movie.poster_path}`} alt={movie.title}/>
                       </li>
                   ))}
               </ul>
           </div>
       </div>
       </div>
      </main>
    </>
  )
}
